CREATE DATABASE IF NOT EXISTS restaurant_db;
USE restaurant_db;

CREATE TABLE IF NOT EXISTS menu (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(50),
  name VARCHAR(100),
  description TEXT,
  price DECIMAL(10, 2)
);

-- Insert all menu items
INSERT INTO menu (id, category, name, description, price) VALUES
(1, 'Taco', 'Steak Taco (3)', 'Onion, Cilantro', 9.99),
(2, 'Taco', 'Beef Taco (3)', 'Pico de Gallo, Lettuce, Cheese', 9.99),
(3, 'Taco', 'Chicken Taco (3)', 'Onion, Cilantro', 9.99),
(4, 'Burrito', 'Steak Burrito', 'Rice, Beans, Cheese, Pico de Gallo', 9.99),
(5, 'Burrito', 'Beef Burrito', 'Rice, Beans, Cheese, Pico de Gallo', 8.99),
(6, 'Burrito', 'Chicken Burrito', 'Rice, Beans, Cheese, Pico de Gallo', 8.99),
(7, 'Quesadilla', 'Steak Quesadilla', 'Pico de Gallo, Lettuce, Sour Cream', 11.99),
(8, 'Quesadilla', 'Beef Quesadilla', 'Pico de Gallo, Lettuce, Sour Cream', 10.99),
(9, 'Quesadilla', 'Chicken Quesadilla', 'Pico de Gallo, Lettuce, Sour Cream', 10.99),
(10, 'Kids Menu', 'Chicken Tenders', '3 pieces, fries, drink', 7.99),
(11, 'Kids Menu', 'Chicken Nuggets', '5 pieces, fries, drink', 7.99),
(12, 'Kids Menu', 'Cheeseburger', 'Fries, drink', 7.99),
(13, 'Wings', '5 Pieces Wings', NULL, 6.99),
(14, 'Wings', '10 Pieces Wings', NULL, 11.99),
(15, 'Wings', '15 Pieces Wings', NULL, 16.99),
(16, 'Wings', '20 Pieces Wings', NULL, 21.99),
(17, 'Wings', '25 Pieces Wings', NULL, 26.99),
(18, 'Wings', '30 Pieces Wings', NULL, 31.99),
(19, 'Fajitas', 'Fajitas', 'Beans, Rice, Salad, Flour Tortillas', 13.99),
(20, 'Plate', 'Gyro Plate', 'Greek Salad or Tabbouleh', 10.99),
(21, 'Plate', 'Chicken Plate', 'Greek Salad or Tabbouleh', 10.99),
(22, 'Plate', 'Falafel Plate', 'Greek Salad or Tabbouleh', 10.99),
(23, 'Plate', 'Mix Plate', 'Greek Salad or Tabbouleh', 11.99),
(24, 'Sandwich', 'Gyro Sandwich', 'Lettuce, Tomato, Feta Cheese', 8.99),
(25, 'Sandwich', 'Chicken Sandwich', 'Lettuce, Tomato, Feta Cheese', 8.99),
(26, 'Sandwich', 'Falafel Sandwich', 'Lettuce, Tomato, Feta Cheese', 8.99),
(27, 'Sandwich', 'Philly Steak Sandwich', 'Lettuce, Tomato, Onion, Mayo', 7.99),
(28, 'Sandwich', 'Homemade Burger', 'Lettuce, Tomato, Onion, Pickles, Mayo', 6.99),
(29, 'Sandwich', 'Grilled Chicken Sandwich', 'Lettuce, Tomato, Onion, Pickles, Mayo', 6.99),
(30, 'Salad', 'Gyro Salad', 'Greek Salad or Tabbouleh', 10.99),
(31, 'Salad', 'Chicken Salad', 'Greek Salad or Tabbouleh', 10.99),
(32, 'Salad', 'Mix Salad', 'Greek Salad or Tabbouleh', 11.49),
(33, 'Drink', 'Soft Drink', NULL, 1.99),
(34, 'Drink', 'Soda Can', NULL, 1.99),
(35, 'Drink', 'Water', NULL, 1.49),
(36, 'Drink', 'Jarritos', NULL, 2.99),
(37, 'Drink', 'Coconut', NULL, 2.99),
(38, 'Drink', 'Gatorade', NULL, 2.49),
(39, 'Drink', 'Pepsi Bottle', NULL, 2.49),
(40, 'Drink', 'Jumex', NULL, 1.99),
(41, 'Drink', 'Monster', NULL, 3.29),
(42, 'Drink', 'Redbull', NULL, 3.99),
(43, 'Drink', 'Bottle Mexican Drink', NULL, 2.99),
(44, 'Side', 'Loaded Fries', NULL, 6.99),
(45, 'Side', 'Fries', NULL, 2.99),
(46, 'Side', 'Salad', NULL, 3.49),
(47, 'Side', 'Rice', NULL, 2.99),
(48, 'Side', 'Beans', NULL, 3.49);
